apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:
    service: rest-api
spec:
  selector:
    app: rest-api
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30002
