version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pushups_logger:
    container_name: pushups_logger
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - .:/pushups_logger
    depends_on:
      - postgres
    entrypoint: ["python", "app.py"]

volumes:
  flask-app-db:
    name: flask-app-db