apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pv-controller
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list", "update", "create", "delete"]
