apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-control-rolebinding
subjects:
- kind: User
  name: dataadmin
  apiGroup: ""
roleRef:
  kind: Role
  name: pv-controller
  apiGroup: ""
