apiVersion: v1
kind: Service
metadata:
  name: {{ include "pl-postgres.fullname" . }}
  labels:
    {{- include "pl-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30001
# targetPort: http
     # protocol: TCP
     # name: http
  selector:
    {{- include "pl-postgres.selectorLabels" . | nindent 4 }}
