apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: frontend-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-ca
  namespace: sandbox
spec:
  isCA: true
  commonName: frontend-ca
  secretName: frontend-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: frontend-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: sandbox
spec:
  ca:
    secretName: frontend-secret
