apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api-chart.fullname" . }}
  labels:
    {{- include "rest-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "rest-api-chart.selectorLabels" . | nindent 4 }}
