apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@domain.com
    privateKeySecretRef:
      name: production
    solvers:
      - http01:
          ingress:
            class: nginx
